services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: podtracker-db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - podtracker-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Isolated PostgreSQL Database for Testing
  test-db:
    image: postgres:15-alpine
    container_name: podtracker-test-db
    restart: always
    ports:
      - "${TEST_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: podtracker_test
    volumes:
      - podtracker-test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d podtracker_test"]

  # Backend Test Runner Service
  test-runner:
    container_name: podtracker-test-runner
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      # Ensure the test runner connects to the test database
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@test-db:5432/podtracker_test
      # Use the same JWT secret as the backend for consistency in tests
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      # Mount the backend source code for live changes and test execution
      - ./backend:/app
      # Exclude node_modules from the host mount to use container's node_modules
      - /app/node_modules
    # Command to run tests. This can be overridden when running `docker-compose run test-runner <command>`
    command: ["npm", "test"]

  # Backend API Service (Node.js)
  backend:
    container_name: podtracker-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend UI Service (React + Vite)
  frontend:
    container_name: podtracker-frontend
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  podtracker-db-data:
    name: podtracker-db-data
  podtracker-test-db-data:
    name: podtracker-test-db-data
