version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: podtrackeruser
      POSTGRES_PASSWORD: podtrackerpassword
      POSTGRES_DB: podtrackerdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: