export const mtgThemes = [
  {
    name: 'Light (Default)',
    value: 'light',
    colors: {
      '--color-background': '#ffffff',
      '--color-text-primary': '#1a202c',
      '--color-text-secondary': '#4a5568',
      '--color-card-background': '#ffffff',
      '--color-border': '#e2e8f0',
      '--color-accent': '#32CD32',
      '--color-button-primary-bg': '#32CD32',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#4a5568',
      '--color-button-secondary-text': '#ffffff',
      '--color-input-bg': '#edf2f7',
      '--color-input-border': '#cbd5e0',
    },
  },
  {
    name: 'Dark',
    value: 'dark',
    colors: {
      '--color-background': '#1a202c',
      '--color-text-primary': '#e2e8f0',
      '--color-text-secondary': '#a0aec0',
      '--color-card-background': '#2d3748',
      '--color-border': '#4a5568',
      '--color-accent': '#32CD32',
      '--color-button-primary-bg': '#32CD32',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#a0aec0',
      '--color-button-secondary-text': '#1a202c',
      '--color-input-bg': '#2d3748',
      '--color-input-border': '#4a5568',
    },
  },
  {
    name: 'Golgari',
    value: 'theme-golgari',
    colors: {
      '--color-background': '#263226',
      '--color-text-primary': '#e0e0e0',
      '--color-text-secondary': '#a0a0a0',
      '--color-card-background': '#3a473a',
      '--color-border': '#556b2f',
      '--color-accent': '#6b8e23',
      '--color-button-primary-bg': '#6b8e23',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#4a554a',
      '--color-button-secondary-text': '#e0e0e0',
      '--color-input-bg': '#3a473a',
      '--color-input-border': '#556b2f',
    },
  },
  {
    name: 'Jeskai',
    value: 'theme-jeskai',
    colors: {
      '--color-background': '#f0f4f8',
      '--color-text-primary': '#2c3e50',
      '--color-text-secondary': '#607d8b',
      '--color-card-background': '#ffffff',
      '--color-border': '#bbdefb',
      '--color-accent': '#2196f3',
      '--color-button-primary-bg': '#e53935',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#90caf9',
      '--color-button-secondary-text': '#2c3e50',
      '--color-input-bg': '#e3f2fd',
      '--color-input-border': '#90caf9',
    },
  },
  {
    name: 'Grixis',
    value: 'theme-grixis',
    colors: {
      '--color-background': '#1a1a1a',
      '--color-text-primary': '#e0e0e0',
      '--color-text-secondary': '#a0a0a0',
      '--color-card-background': '#2c2c2c',
      '--color-border': '#4a4a4a',
      '--color-accent': '#e53935',
      '--color-button-primary-bg': '#e53935',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#4a4a4a',
      '--color-button-secondary-text': '#e0e0e0',
      '--color-input-bg': '#2c2c2c',
      '--color-input-border': '#4a4a4a',
    },
  },
  {
    name: 'White',
    value: 'theme-white',
    colors: {
      '--color-background': '#f8f8f8',
      '--color-text-primary': '#333333',
      '--color-text-secondary': '#666666',
      '--color-card-background': '#ffffff',
      '--color-border': '#cccccc',
      '--color-accent': '#ffd700',
      '--color-button-primary-bg': '#ffd700',
      '--color-button-primary-text': '#333333',
      '--color-button-secondary-bg': '#e0e0e0',
      '--color-button-secondary-text': '#333333',
      '--color-input-bg': '#f0f0f0',
      '--color-input-border': '#cccccc',
    },
  },
  {
    name: 'Azorius',
    value: 'theme-azorius',
    colors: {
      '--color-background': '#e6f0fa',
      '--color-text-primary': '#2c3e50',
      '--color-text-secondary': '#5a7d9a',
      '--color-card-background': '#ffffff',
      '--color-border': '#a7d9f2',
      '--color-accent': '#3498db',
      '--color-button-primary-bg': '#3498db',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#bbdefb',
      '--color-button-secondary-text': '#2c3e50',
      '--color-input-bg': '#f0f8ff',
      '--color-input-border': '#a7d9f2',
    },
  },
  {
    name: 'Naya',
    value: 'theme-naya',
    colors: {
      '--color-background': '#f5f5dc',
      '--color-text-primary': '#4b0000',
      '--color-text-secondary': '#8b4513',
      '--color-card-background': '#ffffff',
      '--color-border': '#a0522d',
      '--color-accent': '#228b22',
      '--color-button-primary-bg': '#dc143c',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#9acd32',
      '--color-button-secondary-text': '#4b0000',
      '--color-input-bg': '#fffaf0',
      '--color-input-border': '#a0522d',
    },
  },
  {
    name: 'Devoid',
    value: 'theme-devoid',
    colors: {
      '--color-background': '#121212',
      '--color-text-primary': '#e0e0e0',
      '--color-text-secondary': '#a0a0a0',
      '--color-card-background': '#212121',
      '--color-border': '#424242',
      '--color-accent': '#8a2be2',
      '--color-button-primary-bg': '#8a2be2',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#424242',
      '--color-button-secondary-text': '#e0e0e0',
      '--color-input-bg': '#212121',
      '--color-input-border': '#424242',
    },
  },
  {
    name: 'Blue',
    value: 'theme-blue',
    colors: {
      '--color-background': '#e0f2f7',
      '--color-text-primary': '#01579b',
      '--color-text-secondary': '#2962ff',
      '--color-card-background': '#ffffff',
      '--color-border': '#81d4fa',
      '--color-accent': '#2196f3',
      '--color-button-primary-bg': '#2196f3',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#bbdefb',
      '--color-button-secondary-text': '#01579b',
      '--color-input-bg': '#e3f2fd',
      '--color-input-border': '#81d4fa',
    },
  },
  {
    name: 'Black',
    value: 'theme-black',
    colors: {
      '--color-background': '#1c1c1c',
      '--color-text-primary': '#e0e0e0',
      '--color-text-secondary': '#a0a0a0',
      '--color-card-background': '#2c2c2c',
      '--color-border': '#424242',
      '--color-accent': '#7b1fa2',
      '--color-button-primary-bg': '#7b1fa2',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#424242',
      '--color-button-secondary-text': '#e0e0e0',
      '--color-input-bg': '#2c2c2c',
      '--color-input-border': '#424242',
    },
  },
  {
    name: 'Red',
    value: 'theme-red',
    colors: {
      '--color-background': '#ffebee',
      '--color-text-primary': '#b71c1c',
      '--color-text-secondary': '#d32f2f',
      '--color-card-background': '#ffffff',
      '--color-border': '#ef9a9a',
      '--color-accent': '#f44336',
      '--color-button-primary-bg': '#f44336',
      '--color-button-primary-text': '#ffffff',
      '--color-button-secondary-bg': '#ffcdd2',
      '--color-button-secondary-text': '#b71c1c',
      '--color-input-bg': '#ffebee',
      '--color-input-border': '#ef9a9a',
    },
  },
];
